### ISSUE TITLE
[3.12.0][jobsub] Unable to View, Edit, or Create Job Designer Documents

### ISSUE THREAD

**Issue by cricket007** [cloudera/hue#551]
Built `release-3.12.0` branch and from the Home page, I have downloaded the example Job Designer documents to get a full list of documents on the Job Designer Editor. When I click on one of the designs, the page flashes with a spinning wheel, then goes back to the design list. I have verified this behavior on two separate installations. 

---

**Build details**

Release: 3.12.0  build with `PREFIX=/usr/share make install`
OS: CentOS 6 & 7  
[Hue behind nginx](http://gethue.com/using-nginx-to-speed-up-hue-3-8-0/)

---

Nothing special in any of the logs, it just confirms I am being redirected between these endpoints on anything I click.

```
GET /jobsub/designs/{id}
GET /jobsub/designs
```

I am able to check a job  and execute it or delete, but am unable to edit or create one. The logs show the `POST`, but I don't see an error otherwise.

**Comment by enricoberti** [comment]
Sorry about that, it was fixed in https://github.com/cloudera/hue/commit/23b51d9c0c27fe9e915c3aabb3c59d193d266ef7

**Comment by cricket007** [comment]
@enricoberti This does not seem to be the same. Saving is not the immediate problem. Viewing the design is being redirected.

**Comment by enricoberti** [comment]
Yep, that was one of the two problems that the same commit fixed :)

**Comment by cricket007** [comment]
Well, I tried that patch, and it didn't fix the problem, so I think you're referring to 1b8ae04f8e9bb4cffe4565ee2eb2a4a3a95f77c6 , which did work

**Comment by enricoberti** [comment]
whoopsie, correct!

**Comment by cricket007** [comment]
Cool. Thanks for the commit link. 
Sorry for the dupe
